# Generated by Django 4.2 on 2026-09-30 19:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_applicant_gender_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='graduation_date',
            field=models.CharField(default=main.models.current_graduation_year, max_length=20, verbose_name='Дата окончания школы'),
        ),
    ]
